### ISSUE TITLE
Decoder sends multiple events if open is called more than once

### ISSUE THREAD

**Issue by TD22057** [nutechsoftware/alarmdecoder#15]
I'm trying to write a robust handler for converting the alarm messages into MQTT.  I have a class that works fine to do this.  But - if needs to be robust in the sense that ser2sock might not be running or might start or stop unexpectedly (or might start after my process in the init order).  So I wrote my process to detect the connection closing and enter a waiting state where it periodically tries to connect again.

The problem is in decoder.py line 229 in open() where it does this:

    self._wire_events()
    self._device.open(baudrate=baudrate, no_reader_thread=no_reader_thread)
    return self

By having open() call wire events every time, the number of events increases every time open() is called because close doesn't undo this.  But the only way to try to connect is to call open() over and over again which causes a lot of problems once a connection is actually made.  Is there a reason why wiring the events isn't done in the constructor one time?

**Comment by weevis** [comment]
Hi,

Calling close will remove all of the wired events

**Comment by TD22057** [comment]
Yes, but in this case open() throws an exception.  So it seems weird/not correct to have to call close() on something that didn't open.

**Comment by endlesscoil** [comment]
This isn't totally resolved yet, but I did run into a similar issue using it in the webapp.  The latest release of the library has support for clearing the bound event handlers individually.  (example: device.on_arm.clear())  Still need to consider how to best rearrange things and create a remove_events() to take care of it all.

**Comment by TD22057** [comment]
What about a different approach like not connecting them at all until the device open works?  I didn't try it but you could then call the open callback explicitly and then wire them up after the connection has been made.

I'm not sure clear() is a good idea either.  An object should manage it's resources and not introduce side affects.  But clear will erase all the callbacks, so if I have a callback set, it's going to disappear even though I didn't remove it.  It seems like the decoder should add it's callback when it's ok to do so, and remove only it's callbacks on destruction or close.  That leaves the state of the device as it was before it was connected.

**Comment by endlesscoil** [comment]
The clear() method was added to the EventHandler class as a general improvement due to issues I was seeing with lambda event handlers and dangling references.  There was really no way to remove bound events if you didn't have a reference to them.  Definitely still need to address wiring the basic events inside of open, as you've suggested.

Initial thoughts would be to:
1. Either wire up the events when opened successfully or checking to make sure we're not already bound, whichever ends up working better.
2. Add something like remove_events() so events can be cleared automatically on close or manually if desired.
3. Change close() so that we don't rely on delete to get rid of the events.

**Comment by TD22057** [comment]
Let me know if you'd like me to take a stab at coding that for you to review.

**Comment by endlesscoil** [comment]
Feel free!

**Comment by f34rdotcom** [comment]
Thanks for the contribution!
